version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: build/api.dockerfile
    image: proxy
    ports:
      - 127.0.0.1:8888:8000
      - 127.0.0.1:8880:8080
    restart: on-failure
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  db:
    build:
      context: ../
      dockerfile: build/postgres.dockerfile
    image: proxy-db
    environment:
      BACKUP: /init.sql
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
