proxy:

  log: "debug"

  sniffer:
    addr: ":8080"

  admin:
    addr: ":8000"

  postgres:
    host: "postgres"
    port: 5432
    db: "db"
    user: "user"
    password: "postgres"
    maxConnections: 10
